package com.vozmediano.mvc.model.entity;


import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Fabricantes generated by hbm2java
 */
@Entity
@Table(name = "fabricantes", catalog = "springdb")
@JsonIgnoreProperties({"productoses","hibernateLazyInitializer"})
public class Fabricantes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String cif;
	private String nombre;
	private String descrip;
	private String domicilio;
	private Set<Productos> productoses = new HashSet<Productos>(0);

	public Fabricantes() {
	}

	public Fabricantes(String cif) {
		this.cif = cif;
	}

	public Fabricantes(String cif, String nombre, String descrip, String domicilio, Set<Productos> productoses) {
		this.cif = cif;
		this.nombre = nombre;
		this.descrip = descrip;
		this.domicilio = domicilio;
		this.productoses = productoses;
	}

	@Id

	@Column(name = "CIF", unique = true, nullable = false, length = 10)
	public String getCif() {
		return this.cif;
	}

	public void setCif(String cif) {
		this.cif = cif;
	}

	@Column(name = "nombre", length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@JsonIgnore
	@Column(name = "descrip", length = 50)
	public String getDescrip() {
		return this.descrip;
	}

	public void setDescrip(String descrip) {
		this.descrip = descrip;
	}

	@JsonIgnore
	@Column(name = "domicilio", length = 30)
	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	@JsonIgnore
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fabricantes")
	public Set<Productos> getProductoses() {
		return this.productoses;
	}

	public void setProductoses(Set<Productos> productoses) {
		this.productoses = productoses;
	}

}
