package com.vozmediano.mvc.model.entity;



import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name = "productos", catalog = "springdb")
public class Productos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int ref;
	private Fabricantes fabricantes;
	private String nombre;
	private Integer precio;

	public Productos() {
	}

	public Productos(int ref) {
		this.ref = ref;
	}

	public Productos(int ref, Fabricantes fabricantes, String nombre, Integer precio) {
		this.ref = ref;
		this.fabricantes = fabricantes;
		this.nombre = nombre;
		this.precio = precio;
	}

	@Id

	@Column(name = "ref", unique = true, nullable = false)
	public int getRef() {
		return this.ref;
	}

	public void setRef(int ref) {
		this.ref = ref;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cif_fabric")
	public Fabricantes getFabricantes() {
		return this.fabricantes;
	}

	public void setFabricantes(Fabricantes fabricantes) {
		this.fabricantes = fabricantes;
	}

	@Column(name = "nombre", length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "precio")
	public Integer getPrecio() {
		return this.precio;
	}

	public void setPrecio(Integer precio) {
		this.precio = precio;
	}

}
