package exUnit4.entity;
// Generated 25 oct 2024, 9:14:26 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Authors generated by hbm2java
 */
@Entity
@Table(name = "authors", catalog = "biblio")
public class Authors implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String cod;
	private String name;
	private Set<Books> bookses = new HashSet<Books>(0);

	public Authors() {
	}

	public Authors(String cod) {
		this.cod = cod;
	}

	public Authors(String cod, String name, Set<Books> bookses) {
		this.cod = cod;
		this.name = name;
		this.bookses = bookses;
	}

	@Id

	@Column(name = "cod", unique = true, nullable = false, length = 5)
	public String getCod() {
		return this.cod;
	}

	public void setCod(String cod) {
		this.cod = cod;
	}

	@Column(name = "name", length = 60)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "authors")
	public Set<Books> getBookses() {
		return this.bookses;
	}

	public void setBookses(Set<Books> bookses) {
		this.bookses = bookses;
	}

}
