package com.vozmediano.entities;
// Generated 4 feb 2025, 8:22:02 by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * Alumnos generated by hbm2java
 */
@Entity
@Table(name = "alumnos", catalog = "examen1hiber")
public class Alumnos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int nia;
	private Municipios municipios;
	private String nombre;
	private String apellidos;

	public Alumnos() {
	}

	public Alumnos(int nia) {
		this.nia = nia;
	}

	public Alumnos(int nia, Municipios municipios, String nombre, String apellidos) {
		this.nia = nia;
		this.municipios = municipios;
		this.nombre = nombre;
		this.apellidos = apellidos;
	}

	@Id

	@Column(name = "nia", unique = true, nullable = false)
	public int getNia() {
		return this.nia;
	}

	public void setNia(int nia) {
		this.nia = nia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_municipio")
	public Municipios getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Municipios municipios) {
		this.municipios = municipios;
	}

	@Column(name = "nombre", length = 15)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "apellidos", length = 20)
	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	@Override
	public String toString() {
		return "nombre=: " + nombre + ", apellidos: " + apellidos;
	}

	
	
	

}
