package com.vozmediano.entities;
// Generated 4 feb 2025, 8:22:02 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Municipios generated by hbm2java
 */
@Entity
@Table(name = "municipios", catalog = "examen1hiber")
public class Municipios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idMunicipio;
	private String nombre;
	private Integer NHabitantes;
	private Set<Alumnos> alumnoses = new HashSet<Alumnos>(0);

	public Municipios() {
	}

	public Municipios(String idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	public Municipios(String idMunicipio, String nombre, Integer NHabitantes, Set<Alumnos> alumnoses) {
		this.idMunicipio = idMunicipio;
		this.nombre = nombre;
		this.NHabitantes = NHabitantes;
		this.alumnoses = alumnoses;
	}

	@Id

	@Column(name = "id_municipio", unique = true, nullable = false, length = 5)
	public String getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(String idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	@Column(name = "nombre", length = 10)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "n_habitantes")
	public Integer getNHabitantes() {
		return this.NHabitantes;
	}

	public void setNHabitantes(Integer NHabitantes) {
		this.NHabitantes = NHabitantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipios")
	public Set<Alumnos> getAlumnoses() {
		return this.alumnoses;
	}

	public void setAlumnoses(Set<Alumnos> alumnoses) {
		this.alumnoses = alumnoses;
	}

	@Override
	public String toString() {
		return "idMunicipio:" + idMunicipio + ", nombre:" + nombre;
	}
	
	

}
